version: "3.8"

services:
  hubble-chatbot-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: hubble_chatbot_ui
    container_name: hubble_chatbot_ui
    ports:
      - "3000:80"
    volumes:
      - .:/app
    env_file:
      - ./.env
